workflows:
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp
      - run: yarn install
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
