workflows:
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
      - image: circleci/postgres:9.6.2-alpine

    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp
      - run: yarn install
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - run:
          name: "database"
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
            JWT_SECRET: coucou
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
