version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  job-name: node-gyp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install node-gyp
          command: yarn global add node-gyp && yarn install
