workflows:
  starter:
    jobs:
      - hello
  install:
    jobs:
      - yarn
      - lint:
          requires:
            - yarn
  tests:
    jobs:
      - test
      - e2e
  yarn:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  checks:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules


  database:
    docker:
      - image: 'circleci/node:12'
        environment:
          DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
          JWT_SECRET: some string you want
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      - image: 'circleci/postgres:9.6.2-alpine'
        environment:
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
          POSTGRES_DB: psdb
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test:e2e
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
